CREATE TABLE
  gold.tb_analise_franquias
AS (
SELECT
ret.COD_FRANQUIA
,ret.NOME_FRANQUIA
,ret.COD_MATERIAL
,ret.DES_MATERIAL
,ret.DES_CATEGORIA
,ret.ESTADO
,ret.VLR_VENDA_FRANQUIA_MATERIAL
,DENSE_RANK() OVER (PARTITION BY RET.COD_FRANQUIA ORDER BY RET.VLR_VENDA_FRANQUIA_MATERIAL DESC ) AS RANK_VENDA_FRANQUIA_MATERIAL
,DENSE_RANK() OVER (PARTITION BY RET.COD_FRANQUIA ORDER BY RET.VLR_VENDA_FRANQUIA_CATEGORIA DESC ) AS RANK_VENDA_FRANQUIA_CATEGORIA
,DENSE_RANK() OVER (PARTITION BY RET.COD_FRANQUIA, RET.DES_CATEGORIA ORDER BY RET.VLR_VENDA_FRANQUIA_MATERIAL DESC ) AS RANK_VENDA_FRANQUIA_MATERIAL_CATEGORIA
FROM (
	SELECT
	tb_vendas_gb.COD_FRANQUIA
	,tb_vendas_gb.NOME_FRANQUIA
	,tb_vendas_gb.COD_MATERIAL
	,tb_vendas_gb.DES_MATERIAL
	,tb_vendas_gb.DES_CATEGORIA
	,tb_vendas_gb.ESTADO
	,ROUND(SUM(tb_vendas_gb.VLR_VENDA),2) AS VLR_VENDA_FRANQUIA_MATERIAL
	,TB_vendas_gb.VLR_VENDA_FRANQUIA_CATEGORIA
	 FROM (	
          SELECT
        tb_vendas.COD_FRANQUIA
        ,tb_vendas.NOME_FRANQUIA
        ,tb_vendas.COD_MATERIAL
        ,tb_vendas.DES_MATERIAL
        ,tb_vendas.DES_CATEGORIA
        ,tb_vendas.ESTADO
        ,tb_vendas.VLR_VENDA
        ,ROUND(SUM(tb_vendas.VLR_VENDA) OVER (PARTITION BY tb_vendas.COD_FRANQUIA, tb_vendas.DES_CATEGORIA),2) AS VLR_VENDA_FRANQUIA_CATEGORIA
        FROM `silver.tb_vendas_gb` as tb_vendas
        ) AS TB_vendas_gb
	 GROUP BY
	 tb_vendas_gb.COD_FRANQUIA
	,tb_vendas_gb.NOME_FRANQUIA
	,tb_vendas_gb.COD_MATERIAL
	,tb_vendas_gb.DES_MATERIAL
	,tb_vendas_gb.DES_CATEGORIA
	,tb_vendas_gb.ESTADO
  ,tb_vendas_gb.VLR_VENDA_FRANQUIA_CATEGORIA
	) RET
ORDER BY ret.cod_franquia, ret.VLR_VENDA_FRANQUIA_MATERIAL
)